name: flexipod
channels:
  - pytorch
  - nvidia
  - open3d-admin
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - absl-py
  - autopep8
  - box2d-py
  - cython 
  - embree
  - gym
  - imageio
  - joblib
  - lxml
  - matplotlib
  - meshio
  - msgpack-python
  - networkx
  - numba
  - numpy
  - open3d
  - pandas
  - pip
  - point_cloud_utils
  - pydot
  - pythonocc-core
  - cudatoolkit=11.3
  - pytorch
  - torchaudio
  - torchvision
  - termcolor
  - rtree=0.9.4
  - scikit-learn
  - seaborn
  - shapely
  - tensorboard
  - tqdm
  - trimesh
  - jupyter
  - jupyter_contrib_nbextensions
  - line_profiler
  - py-opencv
  - pip:
    - hydra-core --pre
    - pybullet
    - gmsh
    # - pyembree # on windows this has to be installed manually