# note: for training flexipod
defaults:
    # - agent: pytorch_sac/agent/sac
    - agent: sac

seed: 1

agent:
    critic_cfg:
        hidden_dim: 256
        hidden_depth: 4
    actor_cfg:
        hidden_dim: 256
        hidden_depth: 4
    batch_size: 512
    discount: 0.999
    # batch_size: 256

# load_model: D:\\repo\\FlexipodFast\\src\\py_src\\exp\\model\\1391031_11777.chpt
# load_model: D:\\repo\\FlexipodFast\\src\\py_src\\exp\\model\\3590240_5811.chpt
train: True
# train: False


num_seed_steps: 10000
# num_seed_steps: 512
# num_seed_steps: 0


# env:
#     _target_: dmc2gym.make
#     domain_name: cheetah
#     task_name: run
#     seed: ${seed}
#     visualize_reward: True
env:
    _target_: flexipod_env.make


# this needs to be specified manually
experiment: test_exp

num_train_steps: 4e6
replay_buffer_capacity: ${num_train_steps}

# eval_frequency: 1000

eval_frequency: 10000
num_eval_episodes: 3

device: "cuda"

# logger
log_frequency: 10000
log_save_tb: true

# video recorder
save_video: False
# save_video: true

# hydra configuration
hydra:
    job:
        # name: sac
        name: ${agent.name}
    run:
        dir: ./exp/${now:%Y.%m.%d.%H%M}_${experiment}
    searchpath:
        - pkg://pytorch_sac/config
